### ISSUE TITLE
Set block (buffer) size doesn't work on my setup

### ISSUE THREAD

**Issue by Sneffel** [Souk21/REAPER-scripts-and-effects#1]
I'm on Windows 10, Reaper (x64) 6.53 portable and not portable indifferently
The scripts to set the buffer size to 64 and 512 don't work
I'm using the Focusrite USB ASIO

**Comment by Souk21** [comment]
Hi, sorry I'm only seeing this now.
There has been new versions since Apr 5,  could you try updating to latest version ?
If the problem persists:
Do other buffer size than 64 and 512 work ?
Try to change the buffer size manually. Does that work ? (in Preferences > Audio device)

**Comment by Sneffel** [comment]
It now works. Thanks a lot. I'd wanted something like this for years. 
Is it possible to incorporate a toggle between 64 and 1024? 
If not, I'll just work with the S&W Action Cycle.
Thanks again.

**Comment by Souk21** [comment]
Have you tried the "Menu" script ?
If you still prefer a toggle, [someone in the forum](https://forum.cockos.com/showpost.php?p=2534936&postcount=3) was able to create one with cycle actions.
Let me know if that doesn't work :)

**Comment by Sneffel** [comment]
A menu defeats the purpose of the toggle 
I also made the cycle action work, but it's a hassle to set up. Every time I reinstall Reaper I need to install a bunch of stuff, manually create the script by copying the action ID, apply and replace the action in the toolbar
